language: php

php:
  - "7"
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"

install: composer install

before_script:
  - mysql -e 'create database dm_test;'
  - cp -f tests/integration/Storage/Db/assets/config.php.sample tests/integration/Storage/Db/assets/config.php

script:
  - vendor/bin/phpunit --report-useless-tests --coverage-clover ./coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7
