language: php

php:
  - "7"
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"

install: composer install

before_script:
  - mysql -e 'create database dm_test;'
  - mysql -e 'CREATE TABLE `test1` (`id` int(11) NOT NULL, `name` varchar(45) DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

script:
  - vendor/bin/phpunit --report-useless-tests --coverage-clover ./coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover

notifications:
  email: true

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7
